### PR TITLE
fix: add https:// to a url that passed to LinkPreview

### PR DESCRIPTION
**Pull request by suliskh**
> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match your own requirements.

## Related Issue

[RKLS-1104](https://ruanggguru.atlassian.net/browse/RKLS-1104)

## Description Of Changes

In this PR, I fixed the url preview on the message input that is not shown if the url doesn't contain an "https://" string

https://user-images.githubusercontent.com/24476578/141885740-83ee4d80-e23c-4b87-ab47-14c6349db0ba.mp4

### Technical Approach

In the current implementation, we use `LinkPreview` component to get the url metadata and render it to the screen. Unfortunately, it only supports url with "https://". So we fixed this issue by prepending "https://" if not present in the url. 

### Additional Changes

Nope 

### Demo

https://user-images.githubusercontent.com/24476578/141885754-0f9a8d6f-d292-4506-80a9-f85dd9f8c00e.mp4

### CODE REVIEW

**Comment by ibedwi** [comment]
Just curious, what will happen if the URL started with "http://" ?

**Comment by suliskh** [comment]
> Just curious, what will happen if the URL started with "http://" ?

It  would still be fetched, Om @dskusuma

**Comment by ibedwi** [comment]
> > Just curious, what will happen if the URL started with "http://" ?
> 
> It would still be fetched, Om

cool! great work om 👍

**Review by ibedwi — APPROVED** [review]
LGTM 🚀

**Pull request merged**
