### PR TITLE
feat(component): add MessageStatus, Icon, and Label

### PR DESCRIPTION
**Pull request by fauzanlinnas**
> This project is a forked version of the [Sendbird UI Kit](https://github.com/sendbird/sendbird-uikit-react) to match with the Ruangguru's internal requirements. Therefore, it is not yet set up to accept pull requests from external contributors. But you can always freely create a forked version from this repository to match with your own requirements.

## Related Issue
[RKLS-932](https://ruanggguru.atlassian.net/browse/RKLS-932)
[RKLS-933](https://ruanggguru.atlassian.net/browse/RKLS-933)
[RKLS-934](https://ruanggguru.atlassian.net/browse/RKLS-934)
[RKLS-935](https://ruanggguru.atlassian.net/browse/RKLS-935)

## Description Of Changes

- [x] Add Icon component to rogu directory
- [x] Add Label component
- [x] Add MessageStatus component
- [x] Handle all message state

### Before
Screen Shot 2021-10-08 at 14 41 40

### After
Screen Shot 2021-10-08 at 14 41 17

### CODE REVIEW

**Comment by suliskh** [comment]
There is a failing check. Please check here mas @fauzanlinnas https://github.com/ruang-guru/sendbird-uikit-react/actions/runs/1319438694

**Comment by fauzanlinnas** [comment]
> There is a failing check. Please check here mas @fauzanlinnas https://github.com/ruang-guru/sendbird-uikit-react/actions/runs/1319438694

jadi penyebab failnya karena aku ganti beberapa `className` dari `"sendbird-..."` jadi `"rogu-..."`. Karena kalo make former className, dia bakal bentrok sama UIKit MessageStatus component (`class`nya ke override). Kira2 solvenya gimana ya mas kalo kaya gini? @suliskh

**Comment by suliskh** [comment]
> > There is a failing check. Please check here mas @fauzanlinnas https://github.com/ruang-guru/sendbird-uikit-react/actions/runs/1319438694
> 
> jadi penyebab failnya karena aku ganti beberapa `className` dari `"sendbird-..."` jadi `"rogu-..."`. Karena kalo make former className, dia bakal bentrok sama UIKit MessageStatus component (`class`nya ke override). Kira2 solvenya gimana ya mas kalo kaya gini? @suliskh

I see, bisa dicoba buat update selector di testcasenya jadi `.rogu-..` yah mas @fauzanlinnas. Trus jangan lupa buat update snapshootnya  dg `npm run test-update-snapshot`

**Review by suliskh — APPROVED** [review]
Kapalkan!

**Pull request merged**
